/*
 * NotesExampleAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using NotesExampleAPI.PCL.Controllers;
using NotesExampleAPI.PCL.Http.Client;
using NotesExampleAPI.PCL.Utilities;

namespace NotesExampleAPI.PCL
{
    public partial class NotesExampleAPIClient
    {

        /// <summary>
        /// Singleton access to Notes controller
        /// </summary>
        public NotesController Notes
        {
            get
            {
                return NotesController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public NotesExampleAPIClient() { }
        #endregion
    }
}