/*
 * NotesExampleAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using NotesExampleAPI.PCL;
using NotesExampleAPI.PCL.Utilities;


namespace NotesExampleAPI.PCL.Models
{
    public class NotesResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private string title;
        private string status;
        private int dueInDays;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("dueInDays")]
        public int DueInDays 
        { 
            get 
            {
                return this.dueInDays; 
            } 
            set 
            {
                this.dueInDays = value;
                onPropertyChanged("DueInDays");
            }
        }
    }
} 