/*
 * NotesExampleAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using NotesExampleAPI.PCL;
using NotesExampleAPI.PCL.Utilities;


namespace NotesExampleAPI.PCL.Models
{
    public class Object : BaseModel 
    {
    }
} 