/*
 * NotesExampleAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using NotesExampleAPI.PCL;
using NotesExampleAPI.PCL.Utilities;

namespace NotesExampleAPI.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum XTrackingExampleEnum
    {
        ACCOUNTING, //TODO: Write general description for this method
        PAYROLL, //TODO: Write general description for this method
        FINANCE, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type XTrackingExampleEnum
    /// </summary>
    public static class XTrackingExampleEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "accounting", "payroll", "finance" };

        /// <summary>
        /// Converts a XTrackingExampleEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The XTrackingExampleEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(XTrackingExampleEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case XTrackingExampleEnum.ACCOUNTING:
                case XTrackingExampleEnum.PAYROLL:
                case XTrackingExampleEnum.FINANCE:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of XTrackingExampleEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of XTrackingExampleEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<XTrackingExampleEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into XTrackingExampleEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed XTrackingExampleEnum value</returns>
        public static XTrackingExampleEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type XTrackingExampleEnum", value));

            return (XTrackingExampleEnum) index;
        }
    }
} 